version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Aa123456*
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=Aa123456*
    ports:
      - "3306:3306"
    volumes:
      - "/home/phablet/Documents/mysql/conf:/etc/mysql/conf.d"
      - "/home/phablet/Documents/mysql/data:/var/lib/mysql"

  phpmyadmin:
    depends_on:
      - mysql
    image: bitnami/phpmyadmin:latest
    restart: always
    links:
      - mysql:mysql
    ports:
      - '18081:8080'
      - '18082:8443'
    container_name: phpmyadmin
    environment:
      - DATABASE_HOST=mysql
      # - DATABASE_USER=root
      # - DATABASE_PASSWORD=Aa123456*
      - DATABASE_PORT_NUMBER=3306
